name: Good Design
favicon: null
layout_spectrum: 0.40154
typography_spectrum: 0.38531
title: The principles of Good Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3e3e3e'
    - '#fd6d24'
    - '#cf4305'
    - '#e4af85'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
