name: Good Design
favicon: null
layout_spectrum: 0.12763
typography_spectrum: 0.13968
title: Good Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74085065-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f08828'
    - '#dfe3ca'
    - '#a8d9d7'
    - '#f66d00'
    - '#6fcfe7'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
